# Generated by Django 3.2.5 on 2022-02-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebBoard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('regdate', models.DateField(auto_now=True)),
                ('viewcnt', models.IntegerField(default=0)),
            ],
        ),
    ]
